# Generated by Django 2.1.7 on 2019-02-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='connector',
        ),
        migrations.AddField(
            model_name='node',
            name='pattern',
            field=models.CharField(default='P01', max_length=16),
        ),
    ]
