# Generated by Django 2.1.5 on 2019-03-27 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_node_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='endNodeId',
        ),
        migrations.RemoveField(
            model_name='path',
            name='startNodeId',
        ),
        migrations.DeleteModel(
            name='Path',
        ),
    ]
